### ISSUE TITLE
angular 2.2 compatible?

### ISSUE THREAD

**Issue by alfupe** [alalonde/ng2-breadcrumbs#3]
Hi there,

I have tried to implement the example to a recently created project that uses angular 2.2.2 and the Router seems to be changed a lot from rc5 thus is not working anymore.

Could you be so kind to update the example to be angular 2.2 compatible? I know it's much to ask, but it would help a lot to people, like me, who do not have enough angular knowledge yet.

Thanks a lot!

**Comment by alalonde** [comment]
Just updated for ng2 2.3.x

**Comment by alfupe** [comment]
Thanks!
